### ISSUE TITLE
Consider upgrading PHP version requirements

### ISSUE THREAD

**Issue by peter279k** [marcocesarato/PHP-Dumper#1]
As title, I think it should bump the PHP version requirements to `php-7.1` at least.

The `php-4.x` and `php-5.x` have been unsupported by official PHP team now.

**Comment by peter279k** [comment]
@marcocesarato, could you explain why closing this issue?

**Comment by marcocesarato** [comment]
Sorry I've not sent the motivation for a mistakes. My bad.
You right but simply it can be used with older php version and If someone have for example an older php version like 5.6.x why don't let use it?!

**Comment by peter279k** [comment]
Hi @marcocesarato, thanks for your concern again.

I think it's fine to let this package require `php-5.6` version at least.

And drop `php-4.x` versions because they're too old :).
