### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by peter279k** [marcocesarato/PHP-Dumper#2]
To make classes worked as we''re expected, it should add unit test.

I think it can use the PHPUnit and integrate Travis CI build to make upcoming commits do unit test works automatically.

**Comment by marcocesarato** [comment]
Good idea i will try to do something soon.

**Comment by marcocesarato** [comment]
Thank you peter for your contribute, as you saw, I've only a little experience on creating tests configurations (usually I work on big projects with prepared configuration for this), than if you add others test or configuration missed they are very welcome :).
If you want you can add yourself on a new contributors section (you just need to add it) on README and I will approve the pull request.

**Comment by peter279k** [comment]
Hi @marcocesarato, thanks for your reply. I'm happy to see that you concern my contributions a lot :).

I can help this repository to have the completed tests with unit tests and Travis CI build integration.
