### ISSUE TITLE
Consider integrating coding style rule and check tool

### ISSUE THREAD

**Issue by peter279k** [marcocesarato/PHP-Dumper#6]
To let the package be consistency for the coding style.

I think this issue should be concerned. And my suggested coding style tools are as follows:

- [PHP_CondSniffer](https://github.com/squizlabs/PHP_CodeSniffer)
- [ PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer)

@marcocesarato, do you have any idea about this?

Which coding style tool you prefer?

Which coding style rule you follows? `PSR-2` or others?

Thanks :).

**Comment by marcocesarato** [comment]
I follow PSR-1/PSR-2. PHP CS Fixer is better i think.

**Comment by peter279k** [comment]
@marcocesarato, thanks for your reply and suggestion.

Let's use the `PHP-CS-Fixer` to resolve this issue :).
